<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BarangSnackSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \App\Models\BarangSnack::insert([
            [
                'nama' => 'Kerupuk Tahu',
                'harga' => '500',
                'kategori' => 'Kerupuk',
                'stok' => 100,
                'gambar' => 'kerupuk_tahu.png',
            ],
            [
                'nama' => 'Kerupuk Kuning',
                'harga' => '2000',
                'kategori' => 'Kerupuk',
                'stok' => 100,
                'gambar' => 'kerupuk_kuning.png',
            ],
            [
                'nama' => 'Kerupuk Putih',
                'harga' => '500',
                'kategori' => 'Kerupuk',
                'stok' => 100,
                'gambar' => 'kerupuk_putih.png',
            ],
            [
                'nama' => 'Aneka Roti',
                'harga' => '5000',
                'kategori' => 'Roti',
                'stok' => 100,
                'gambar' => 'aneka_roti.png',
            ],
            [
                'nama' => 'Pizza',
                'harga' => '7000',
                'kategori' => 'Pizza',
                'stok' => 100,
                'gambar' => 'pizza.png',
            ],
            [
                'nama' => 'Masker Biasa',
                'harga' => '1000',
                'kategori' => 'Masker',
                'stok' => 100,
                'gambar' => 'masker_biasa.png',
            ],
            [
                'nama' => 'Masker Duckbill',
                'harga' => '1000',
                'kategori' => 'Masker',
                'stok' => 100,
                'gambar' => 'masker_duckbill.png',
            ],
            [
                'nama' => 'Masker KF94',
                'harga' => '2000',
                'kategori' => 'Masker',
                'stok' => 100,
                'gambar' => 'masker_kf94.png',
            ],
            [
                'nama' => 'Hoho Rasa Balado',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'hoho_balado.png',
            ],
            [
                'nama' => 'Dark Chocolate',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'dark_chocolate.png',
            ],
            [
                'nama' => 'Black Chocolate',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'black_chocolate.png',
            ],
            [
                'nama' => 'Black Blueberry',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'black_blueberry.png',
            ],
            [
                'nama' => 'Medan Jaya',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'medan_jaya.png',
            ],
            [
                'nama' => 'Black Strawberry',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'black_strawberry.png',
            ],
            [
                'nama' => 'Chitato Lite',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'chitato_lite.png',
            ],
            [
                'nama' => 'Kido',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'kido.png',
            ],
            [
                'nama' => 'Siip Corn',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'siip_corn.png',
            ],
            [
                'nama' => 'Siip Richeese',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'siip_richeese.png',
            ],
            [
                'nama' => 'Siip Richoco',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'siip_richoco.png',
            ],
            [
                'nama' => 'Chiki Twist Roasted Corn',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'chiki_corn.png',
            ],
            [
                'nama' => 'Apilo Wafer Pandan',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'apilo_pandan.png',
            ],
            [
                'nama' => 'Apilo Wafer Chocolate',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'apilo_chocolate.png',
            ],
            
            [
                'nama' => 'Bakso Bakar',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'bakso_bakar.png',
            ],
            
            [
                'nama' => 'Opak',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'opak.png',
            ],
            
            [
                'nama' => 'Nabati Wafer Coklat',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'nabati_coklat.png',
            ],            
            [
                'nama' => 'Nabati Wafer Keju',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'nabati_keju.png',
            ],            
            [
                'nama' => 'Oreo Original',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'oreo_original.png',
            ],
            [
                'nama' => 'Oreo Strawberry',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'oreo_strawberry.png',
            ],
            [
                'nama' => 'Oreo Chocolate',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'oreo_chocolate.png',
            ],
            [
                'nama' => 'Slai Olai Nanas',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'slai_nanas.png',
            ],
            [
                'nama' => 'Slai Olai Strawberry',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'slai_strawberry.png',
            ],
            [
                'nama' => 'Beng Beng',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'beng_beng.png',
            ],
            [
                'nama' => 'Nexstar Brownies',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'nexstar_brownies.png',
            ],
            [
                'nama' => 'Nabati Ahh',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'nabati_ahh.png',
            ],
            [
                'nama' => 'Kalpa RP',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'kalpa_rp.png',
            ],
            [
                'nama' => 'Choki Stick',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'choki_stick.png',
            ],
            [
                'nama' => 'Choki Choki',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'choki_choki.png',
            ],
            [
                'nama' => 'Malkist Abon',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'malkist_abon.png',
            ],
            [
                'nama' => 'Malkist Cokelat',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'malkist_cokelat.png',
            ],
            [
                'nama' => 'Malkist Cokelat Kelapa',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'malkist_kelapa.png',
            ],
            [
                'nama' => 'Better',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'better.png',
            ],
            [
                'nama' => 'Nextar Nastar',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'nexstar_nastar.png',
            ],
            [
                'nama' => 'Arden',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'arden.png',
            ],
            [
                'nama' => 'Toyaki',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'toyaki.png',
            ],
            [
                'nama' => 'Vegetable Cheese',
                'harga' => '2500',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'vegetable_cheese.png',
            ],
            [
                'nama' => 'Marie Gold',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'marie_gold.png',
            ],
            [
                'nama' => 'Marie Gold Milk Chocolate',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'marie_gold_chocolate.png',
            ],
            [
                'nama' => 'Biskuat Bolu',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'biskuat_bolu.png',
            ],
            [
                'nama' => 'Oreo Softcake',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'oreo_softcake.png',
            ],
            [
                'nama' => 'KejuCake',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'kejucake.png',
            ],
            [
                'nama' => 'Chocopie Coklat',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'chocopie_coklat.png',
            ],
            [
                'nama' => 'Chocopie Coklat Keju',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'chocopie_keju.png',
            ],
            [
                'nama' => 'Tricks',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'tricks.png',
            ],
            [
                'nama' => 'Garuda Rosta',
                'harga' => '2000',
                'kategori' => 'Kacang',
                'stok' => 100,
                'gambar' => 'garuda_rosta.png',
            ],
            [
                'nama' => 'Astor Singles',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'astor_singles.png',
            ],
            [
                'nama' => 'Good Time',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'good_time.png',
            ],
            [
                'nama' => 'Roti Kacang Cap HIU',
                'harga' => '2000',
                'kategori' => 'Roti',
                'stok' => 100,
                'gambar' => 'roti_kacang.png',
            ],
            [
                'nama' => 'Ahh Coklat',
                'harga' => '500',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'ahh_coklat.png',
            ],
            [
                'nama' => 'Wafello',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'wafello.png',
            ],
            [
                'nama' => 'Baricho',
                'harga' => '500',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'good_time.png',
            ],
            [
                'nama' => 'Sari Gandum',
                'harga' => '6500',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'sari_gandum.png',
            ],
            [
                'nama' => 'Borobudur',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'borobudur.png',
            ],
            [
                'nama' => 'Oreo Wafer Choco',
                'harga' => '7500',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'oreo_wafer_choco.png',
            ],
            [
                'nama' => 'Hatari Peanut',
                'harga' => '5000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'hatari_peanut.png',
            ],
            [
                'nama' => 'Gery Coklat',
                'harga' => '7000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'gery_coklat.png',
            ],
            [
                'nama' => 'Hatari Malkist',
                'harga' => '7000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'hatari_malkist.png',
            ],
            [
                'nama' => 'Larutan Penyegar Kaleng',
                'harga' => '7000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'larutan_penyegar_kaleng.png',
            ],
            [
                'nama' => 'Astor Double Coklat',
                'harga' => '5000',
                'kategori' => 'Snack',
                'stok' => 100,
                'gambar' => 'good_time.png',
            ],
            [
                'nama' => 'Luwak White Koffee',
                'harga' => '6000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'luwak_white_koffee.png',
            ],
            [
                'nama' => 'Buavita Jambu',
                'harga' => '8000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'buavita_jambu.png',
            ],
            [
                'nama' => 'ABC Choco Malt',
                'harga' => '4500',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'abc_choco_malt.png',
            ],
            [
                'nama' => 'Tora Cafe Botol',
                'harga' => '4000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'tora_cafe_botol.png',
            ],
            [
                'nama' => 'Good Day',
                'harga' => '7000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'good_day.png',
            ],
            [
                'nama' => 'Kopiko Lucky Day',
                'harga' => '6000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'kopiko_lucky_day.png',
            ],
            [
                'nama' => 'Kopiko 78',
                'harga' => '7000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'kopiko_78.png',
            ],
            [
                'nama' => 'Nescafe Latte',
                'harga' => '8000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'nescafe_latte.png',
            ],
            [
                'nama' => 'Fruit Tea',
                'harga' => '5000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'fruit_tea.png',
            ],
            [
                'nama' => 'Sosro Botol',
                'harga' => '5000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'sosro_botol.png',
            ],
            [
                'nama' => 'Teh Pucuk Harum',
                'harga' => '5000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'teh_pucuk_harum.png',
            ],
            [
                'nama' => 'Floridina',
                'harga' => '4000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'floridina.png',
            ],
            [
                'nama' => 'Fruit Tea Apel',
                'harga' => '3000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'fruit_tea_apel.png',
            ],
            [
                'nama' => 'Teh Botol Sosro',
                'harga' => '3000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'teh_botol_sosro.png',
            ],
            [
                'nama' => 'Bear Brand',
                'harga' => '11000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'bear_brand.png',
            ],
            [
                'nama' => 'Dbest Cincau',
                'harga' => '5000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'dbest_cincau.png',
            ],
            [
                'nama' => 'Dbest Sarang Burung',
                'harga' => '5000',
                'kategori' => 'Minuman',
                'stok' => 100,
                'gambar' => 'dbest_sarang_burung.png',
            ],
            [
                'nama' => 'Ciptadent Formula',
                'harga' => '4000',
                'kategori' => 'Sikat Gigi',
                'stok' => 100,
                'gambar' => 'ciptadent_formula.png',
            ],
            [
                'nama' => 'Rexona Passion',
                'harga' => '20000',
                'kategori' => 'Deodorant',
                'stok' => 100,
                'gambar' => 'rexona_passion.png',
            ],
            [
                'nama' => 'Elips',
                'harga' => '2000',
                'kategori' => 'Vitamin',
                'stok' => 100,
                'gambar' => 'elips.png',
            ],
            [
                'nama' => 'Gilette Blue II',
                'harga' => '9000',
                'kategori' => 'Pisau Cukur',
                'stok' => 100,
                'gambar' => 'gilette_blue.png',
            ],
            [
                'nama' => 'Daia',
                'harga' => '5000',
                'kategori' => 'Deterjen',
                'stok' => 100,
                'gambar' => 'daia.png',
            ],
            [
                'nama' => 'Rinso',
                'harga' => '1000',
                'kategori' => 'Deterjen',
                'stok' => 100,
                'gambar' => 'rinso.png',
            ],
            [
                'nama' => 'Shampoo',
                'harga' => '1000',
                'kategori' => 'Shampoo',
                'stok' => 100,
                'gambar' => 'shampoo.png',
            ],
            [
                'nama' => 'Ekonomi Sabun Cream',
                'harga' => '2500',
                'kategori' => 'Sabun Colek',
                'stok' => 100,
                'gambar' => 'ekonomi_sabun_cream.png',
            ],
            [
                'nama' => 'Hansaplast',
                'harga' => '500',
                'kategori' => 'Hansaplast',
                'stok' => 100,
                'gambar' => 'hansaplast.png',
            ],
            [
                'nama' => 'Box Sabun Mandi',
                'harga' => '5000',
                'kategori' => 'Box',
                'stok' => 100,
                'gambar' => 'box_sabun_mandi.png',
            ],
            [
                'nama' => 'Emeron Lovely',
                'harga' => '9000',
                'kategori' => 'Body Lotion',
                'stok' => 100,
                'gambar' => 'emeron_lovely.png',
            ],
            [
                'nama' => 'Minyak Kayu Putih',
                'harga' => '6500',
                'kategori' => 'Obat',
                'stok' => 100,
                'gambar' => 'minyak_kayu_putih.png',
            ],
            [
                'nama' => 'Tora Cafe Saset',
                'harga' => '1000',
                'kategori' => 'Minuman Saset',
                'stok' => 100,
                'gambar' => 'tora_cafe_saset.png',
            ],
            [
                'nama' => 'Energen',
                'harga' => '2000',
                'kategori' => 'Minuman Saset',
                'stok' => 100,
                'gambar' => 'energen.png',
            ],
            [
                'nama' => 'Dancow',
                'harga' => '4000',
                'kategori' => 'Minuman Saset',
                'stok' => 100,
                'gambar' => 'dancow.png',
            ],
            [
                'nama' => 'Nutrisari',
                'harga' => '1500',
                'kategori' => 'Minuman Saset',
                'stok' => 100,
                'gambar' => 'nutrisari.png',
            ],
            [
                'nama' => 'Chocolatos Drink',
                'harga' => '2000',
                'kategori' => 'Minuman Saset',
                'stok' => 100,
                'gambar' => 'chocolatos_drink.png',
            ],
            [
                'nama' => 'Drink Beng Beng',
                'harga' => '2000',
                'kategori' => 'Minuman Saset',
                'stok' => 100,
                'gambar' => 'drink_beng_beng.png',
            ],
            [
                'nama' => 'Milo',
                'harga' => '2000',
                'kategori' => 'Minuman Saset',
                'stok' => 100,
                'gambar' => 'milo.png',
            ],      
        ]);
    }
}
