<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BarangSnackSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \App\Models\BarangSnack::insert([
            [
                'nama' => 'Kerupuk Tahu',
                'harga' => '500',
                'kategori' => 'Kerupuk',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Kerupuk Kuning',
                'harga' => '2000',
                'kategori' => 'Kerupuk',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Kerupuk Putih',
                'harga' => '500',
                'kategori' => 'Kerupuk',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Aneka Roti',
                'harga' => '5000',
                'kategori' => 'Roti',
                'stok' => 20,
                'gambar' => 'bread.png',
            ],
            [
                'nama' => 'Pizza',
                'harga' => '7000',
                'kategori' => 'Pizza',
                'stok' => 20,
                'gambar' => 'pizza.png',
            ],
            [
                'nama' => 'Masker Biasa',
                'harga' => '1000',
                'kategori' => 'Masker',
                'stok' => 20,
                'gambar' => 'mask.png',
            ],
            [
                'nama' => 'Masker Duckbill',
                'harga' => '1000',
                'kategori' => 'Masker',
                'stok' => 20,
                'gambar' => 'mask.png',
            ],
            [
                'nama' => 'Masker KF94',
                'harga' => '2000',
                'kategori' => 'Masker',
                'stok' => 20,
                'gambar' => 'mask.png',
            ],
            [
                'nama' => 'Hoho Rasa Balado',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Dark Chocolate',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Black Chocolate',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Black Blueberry',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Medan Jaya',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Black Strawberry',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Chitato Lite',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Kido',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Siip Corn',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Siip Richeese',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Siip Richoco',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Chiki Twist Roasted Corn',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Apilo Wafer Pandan',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Apilo Wafer Chocolate',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            
            [
                'nama' => 'Bakso Bakar',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            
            [
                'nama' => 'Opak',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            
            [
                'nama' => 'Nabati Wafer Coklat',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],            
            [
                'nama' => 'Nabati Wafer Keju',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],            
            [
                'nama' => 'Oreo Original',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Oreo Strawberry',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Oreo Chocolate',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Slai Olai Nanas',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Slai Olai Strawberry',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Beng Beng',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Nexstar Brownies',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Nabati Ahh',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Kalpa RP',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Choki Stick',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Choki Choki',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Malkist Abon',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Malkist Cokelat',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Malkist Cokelat Kelapa',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Better',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Nextar Nastar',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Arden',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Toyaki',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Vegetable Cheese',
                'harga' => '2500',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Marie Gold',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Marie Gold Milk Chocolate',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Biskuat Bolu',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Oreo Softcake',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'KejuCake',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Chocopie Coklat',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Chocopie Coklat Keju',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Tricks',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Garuda Rosta',
                'harga' => '2000',
                'kategori' => 'Kacang',
                'stok' => 20,
                'gambar' => 'peanuts.png',
            ],
            [
                'nama' => 'Astor Singles',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Good Time',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Roti Kacang Cap HIU',
                'harga' => '2000',
                'kategori' => 'Roti',
                'stok' => 20,
                'gambar' => 'bread.png',
            ],
            [
                'nama' => 'Ahh Coklat',
                'harga' => '500',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Wafello',
                'harga' => '2000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Baricho',
                'harga' => '500',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Sari Gandum',
                'harga' => '6500',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Borobudur',
                'harga' => '1000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Oreo Wafer Choco',
                'harga' => '7500',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Hatari Peanut',
                'harga' => '5000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Gery Coklat',
                'harga' => '7000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Hatari Malkist',
                'harga' => '7000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Larutan Penyegar Kaleng',
                'harga' => '7000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Astor Double Coklat',
                'harga' => '5000',
                'kategori' => 'Snack',
                'stok' => 20,
                'gambar' => 'snacks.png',
            ],
            [
                'nama' => 'Luwak White Koffee',
                'harga' => '6000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Buavita Jambu',
                'harga' => '8000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'ABC Choco Malt',
                'harga' => '4500',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Tora Cafe Botol',
                'harga' => '4000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Good Day',
                'harga' => '7000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Kopiko Lucky Day',
                'harga' => '6000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Kopiko 78',
                'harga' => '7000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Nescafe Latte',
                'harga' => '8000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Fruit Tea',
                'harga' => '5000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Sosro Botol',
                'harga' => '5000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Teh Pucuk Harum',
                'harga' => '5000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Floridina',
                'harga' => '4000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Fruit Tea Apel',
                'harga' => '3000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Teh Botol Sosro',
                'harga' => '3000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Bear Brand',
                'harga' => '11000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Dbest Cincau',
                'harga' => '5000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Dbest Sarang Burung',
                'harga' => '5000',
                'kategori' => 'Minuman',
                'stok' => 20,
                'gambar' => 'drink.png',
            ],
            [
                'nama' => 'Ciptadent Formula',
                'harga' => '4000',
                'kategori' => 'Sikat Gigi',
                'stok' => 20,
                'gambar' => 'tooth-brush.png',
            ],
            [
                'nama' => 'Rexona Passion',
                'harga' => '20000',
                'kategori' => 'Deodorant',
                'stok' => 20,
                'gambar' => 'deodorant.png',
            ],
            [
                'nama' => 'Elips',
                'harga' => '2000',
                'kategori' => 'Vitamin',
                'stok' => 20,
                'gambar' => 'vitamin.png',
            ],
            [
                'nama' => 'Gilette Blue II',
                'harga' => '9000',
                'kategori' => 'Pisau Cukur',
                'stok' => 20,
                'gambar' => 'razor.png',
            ],
            [
                'nama' => 'Daia',
                'harga' => '5000',
                'kategori' => 'Deterjen',
                'stok' => 20,
                'gambar' => 'detergent.png',
            ],
            [
                'nama' => 'Rinso',
                'harga' => '1000',
                'kategori' => 'Deterjen',
                'stok' => 20,
                'gambar' => 'detergent.png',
            ],
            [
                'nama' => 'Shampoo',
                'harga' => '1000',
                'kategori' => 'Shampoo',
                'stok' => 20,
                'gambar' => 'shampoo.png',
            ],
            [
                'nama' => 'Ekonomi Sabun Cream',
                'harga' => '2500',
                'kategori' => 'Sabun Colek',
                'stok' => 20,
                'gambar' => 'soap.png',
            ],
            [
                'nama' => 'Hansaplast',
                'harga' => '500',
                'kategori' => 'Hansaplast',
                'stok' => 20,
                'gambar' => 'patch.png',
            ],
            [
                'nama' => 'Box Sabun Mandi',
                'harga' => '5000',
                'kategori' => 'Box',
                'stok' => 20,
                'gambar' => 'soap.png',
            ],
            [
                'nama' => 'Emeron Lovely',
                'harga' => '9000',
                'kategori' => 'Body Lotion',
                'stok' => 20,
                'gambar' => 'lotion.png',
            ],
            [
                'nama' => 'Minyak Kayu Putih',
                'harga' => '6500',
                'kategori' => 'Obat',
                'stok' => 20,
                'gambar' => 'perfume.png',
            ],
            [
                'nama' => 'Tora Cafe Saset',
                'harga' => '1000',
                'kategori' => 'Minuman Saset',
                'stok' => 20,
                'gambar' => 'sachet.png',
            ],
            [
                'nama' => 'Energen',
                'harga' => '2000',
                'kategori' => 'Minuman Saset',
                'stok' => 20,
                'gambar' => 'sachet.png',
            ],
            [
                'nama' => 'Dancow',
                'harga' => '4000',
                'kategori' => 'Minuman Saset',
                'stok' => 20,
                'gambar' => 'sachet.png',
            ],
            [
                'nama' => 'Nutrisari',
                'harga' => '1500',
                'kategori' => 'Minuman Saset',
                'stok' => 20,
                'gambar' => 'sachet.png',
            ],
            [
                'nama' => 'Chocolatos Drink',
                'harga' => '2000',
                'kategori' => 'Minuman Saset',
                'stok' => 20,
                'gambar' => 'sachet.png',
            ],
            [
                'nama' => 'Drink Beng Beng',
                'harga' => '2000',
                'kategori' => 'Minuman Saset',
                'stok' => 20,
                'gambar' => 'sachet.png',
            ],
            [
                'nama' => 'Milo',
                'harga' => '2000',
                'kategori' => 'Minuman Saset',
                'stok' => 20,
                'gambar' => 'sachet.png',
            ],      
        ]);
    }
}
